- name: Break down master
  become: yes
  become_method: sudo
  shell: kubeadm reset -f

- name: Installing packages
  become: yes
  become_method: sudo
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items: "{{ packages }}"

- name: Download gpg
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /home/ubuntu/docker.gpg
    mode: 0440

- name: Install gpg key
  become: yes
  become_method: sudo
  shell: "apt-key add - < /home/ubuntu/docker.gpg"

- name: Disable swap
  become: yes
  become_method: sudo
  shell: "swapoff -a"

- name: Add swapoff to fstab
  become: yes
  become_method: sudo
  shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Add URL k8s to repo list
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes

- name: Copy config template file
  become: yes
  become_method: sudo
  template:
    src=../files/daemon.json
    dest=/etc/docker/daemon.json
    owner=root group=root mode=0644

- name: Mkdir docker.service.d
  become: yes
  become_method: sudo
  shell: mkdir -p /etc/systemd/system/docker.service.d

- name: Restart service systemd
  become: yes
  become_method: sudo
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: Capture node IP
  become: yes
  become_method: sudo
  shell: ifconfig | grep enp0s3 -A 1 | grep inet | cut -d ':' -f 2 | cut -d ' ' -f 1
  register: ip

- name: trim ip
  shell: echo "{{ip.stdout | to_json | replace('\n', '') | replace('[', '') | replace(']', '')}}"
  register: ip_trim

- name: Set /etc/hostname
  become: yes
  become_method: sudo
  shell: hostnamectl set-hostname node-worker-{{ip_trim.stdout}}

- lineinfile:
    destfile: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1        node-worker-{{ip_trim.stdout}}"
    owner: root
    group: root
    mode: 0644

- name: Kubeadmin node deploy
  become: yes
  become_method: sudo
  shell: "{{install_command}}"
