apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-ci-deployment
  labels:
    app: jenkins-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-v1
  template:
    metadata:
      labels:
        app: jenkins-v1
    spec:
      containers:
      - name: jenkins-master
        image: jenkinsci/blueocean
        ports:
        - name: http-port
          containerPort: 8080
        - name: jnlp-port
          containerPort: 31234
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: nfs-node-vol
      volumes:
        - name: nfs-node-vol
          hostPath:
            path: /home/ubuntu/jenkins_home
